### PR TITLE
Clean Imports

### PR DESCRIPTION
**Pull request by smsutherland**
There are a lot of unused imports in slick.py and other files don't have imports at the top of them at all. I commented the imports out rather than delete them outright so that it is clear which imports were removed.

Additionally, cleaning imports resolved the name conflict between astropy.units and yt.units mentioned in `densityProfile` and affecting `submm_luminosity`.

Apologies for the last 3 commits being a mess. They just a product of me being bad at git unfortunately.

### CODE REVIEW

**Comment by smsutherland** [comment]
Oh also, I replaced append with concat since pandas complained that use of append was deprecated.

**Comment by rdotanirudh** [comment]
I was going to change this but realised you've done it already. Thanks! Also, isn't it sufficient to have all the imports on just slick.py? Only the functions of the other .py files are called anyway.

**Comment by smsutherland** [comment]
No. The imports don't get passed to other files when a function calls into them. Each file needs to have its own set of imports.

**Comment by karolinagarcia** [comment]
Hey guys! Apologies for the late reply here... I'm still getting used to git myself. Thanks Sagan for cleaning the imports, and Anirudh for the great question. I also get confused on where to place the imports sometimes. I had to make some changes to the code. When I was running on my computer, I had everything working, but I did some automations to make it usable by everyone that ended up messing up with the code. I fixed those and it should be running now. Sagan, as we talked yesterday, I'm just gonna ask you to do the imports' cleaning on the current version of the code. Thanks a lot!

**Comment by smsutherland** [comment]
Alright. I'll close this PR and submit a new one for the latest changes

**Pull request closed without merging**
